[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "eth-account>=0.13.5",
    "hdwallet>=3.3.0",
    "mnemonic>=0.21",
    "requests>=2.32.3",
    "sendgrid>=6.11.0",
    "web3>=7.8.0",
]
